### ISSUE TITLE
O2KR9 - Review perks/benefits 

### ISSUE THREAD

**Issue by jonathanbarker** [status-im/people-ops#23]
Review the perks/benefits currently provided for 2019.

**Comment by jonathanbarker** [comment]
Completed. 2018 perks/benefits to remain, with update to approvals for conferences & travel (taking into account the budget owners/approvers we have).

**Comment by ceripower** [comment]
Updated [Parental Leave](https://people-ops.status.im/parental-leave/) page so that the language is less definitive - we don't want to promise everyone can take the amount of leave that's customary locally, but we'll try and accommodate people where we can. (e.g. In some jurisdictions, parental leave is up to a year, which isn't something that would be responsible for us to promise right now given market conditions and our objectives). People should start a discussion with People Ops and go from there.

**Comment by ceripower** [comment]
Minor cosmetic edits to [Sick Leave](https://people-ops.status.im/if-youre-sick/) policy - no change in substance

**Comment by ceripower** [comment]
@DanBigM - are we still asking CH/DE employees to submit hourly timesheets? Wondering if [this](https://people-ops.status.im/time-off/) page needs to be amended.

**Comment by ceripower** [comment]
Minor edits to [Getting Paid](https://people-ops.status.im/getting-paid/) to reflect DAI as an option, plus explaining the approval flow for changes to crypto split.

**Comment by ceripower** [comment]
Made the request around reports being a minimum of EUR 50 in [Filing Expenses](https://people-ops.status.im/filing-expenses/) being more of an ask than a favour.

**Comment by ceripower** [comment]
@rajanie on Device policy, can we now change the following to say that Yubikeys are an approved expense? I think we agreed on it being ok in the last POps hangout.

https://hackmd.io/w05YbPzJSHG1lnS5fSS4Eg
https://people-ops.status.im/laptop-and-phone/

Side note, I updated the people ops page on devices to mention that the device allowance is non transferrable, and that we'll only consider other non laptop/phone devices if there's a business need.

**Comment by ceripower** [comment]
@rajanie Draft page on learning [here](https://people-ops-status.ghost.io/ghost/#/editor/5b9fb6e37d3ba700cbac2c95), just to double check, are books/learning no longer expensable as well as conferences?

**Comment by DanBigM** [comment]
@ceripower Yes, we do. I still have it on the to do list that we can get rid of this.

**Comment by ceripower** [comment]
@rajanie -regarding the travel policy, can we add some clarification about what falls into each flight budget category?:

> - Flights in Europe 200 USD/EUR or below.
>- International Flights within Europe 200 - 500 USD / EUR (Flights within the US) or below.
>- International not within Europe 500 - 1000 EUR or below.

What's the difference between a flight in Europe and an international flight within Europe? Also what about a quick flight between two US cities?

I built out the `Approval` section from:

> ###Approvals
Please speak with your team lead and make sure there is agreement on the value of the event you're planning to attend. Expenses incurred will come out of team budgets. All budgets are already set for teams. 

to:

> ###Getting Approval
Here's what to do if you want to plan some travel:
>1. If the cost of the trip has already been factored in to your team's budget, you don't need to get additional approval for the costs, go to (3)
>2. If the trip is cross-team or outside of regular budgeting, please put together a proposal including attendees, trip purpose and costs, and run this for cost approval by People Ops and your team lead.
>3. Add a copy of all proposals/trip outlines on Discuss, for transparency and knowledge sharing.

lmk what you think

**Comment by rajanie** [comment]
@ceripower: Yes, Yubikey's are expensable since people might be required to use them to login most applications. But since we don't have a time line for when this is rolling out, mostly months away, I don't feel it needs to be added to the devices just yet. Just in case also, it doesn't go through. 

Flights: I will update the flights. There is no difference between flights in Europe and International Europe Flights. My bad.
